### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by jaxily** [Banbury/UnityPsdImporter#10]
Hello, I am having difficulty getting this to work.  I put the two files in the root directory of the Unity Project, but still getting the error below.

Assets/PhotoShopFileType/PsdFile/Util.cs(130,7): error CS0227: Unsafe code requires the `unsafe' command line option to be specified

**Comment by jaxily** [comment]
Do you have a sample project that you can share?  That would be great, thanks

**Comment by playemgames** [comment]
From the readme:

"To compile the Unity PSD Importer in the Unity3D Editor you must have the files gmcs.rsp and smcs.rsp with "-unsafe" in the first line of the files in the root directory of your project. Otherwise you can compile the code as a DLL and it will also work in the editor."

**Comment by jaxily** [comment]
The files are in the root directory of the project so not sure what I am missing

Regards,
Jake

**Comment by playemgames** [comment]
Try looking at how I created a project here:

https://www.youtube.com/watch?v=bsd8lpesiTE&feature=player_detailpage#t=140
